apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: krishi
type: Opaque
stringData:
  PORT: "5000"
  NODE_ENV: "production"
  MONGODB_URI: "replace_me"
  JWT_SECRET: "replace_me"
  JWT_REFRESH_SECRET: "replace_me"
  JWT_EXPIRE: "24h"
  JWT_REFRESH_EXPIRE: "7d"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "replace_me"
  EMAIL_PASSWORD: "replace_me"
  OTP_EXPIRE_MINUTES: "10"
  FRONTEND_URL: "replace_with_frontend_lb_url"
  GEMINI_API_KEY: "replace_me"
  MARKET_PRICE_API_URL: "https://api.data.gov.in/resource"
  MARKET_PRICE_API_KEY: "replace_me"
  WEATHER_API_URL: "https://api.openweathermap.org/data/2.5"
  WEATHER_API_KEY: "replace_me"
  GOV_SCHEME_API_URL: "https://api.data.gov.in/resource"
  GOV_SCHEME_API_KEY: "replace_me"
